### ISSUE TITLE
I received this error when i called the code in the initState or anywhere other place.

### ISSUE THREAD

**Issue by rafay-tariq** [kuzzleio/sdk-dart#42]
[ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: WebSocketException: Connection to 'https://kuzzle.folksinc.com#' was not upgraded to websocket
E/flutter (13901): #0 _WebSocketImpl.connect.<anonymous closure>.error (dart:_http/websocket_impl.dart:1058:9)
E/flutter (13901): #1 _WebSocketImpl.connect.<anonymous closure> (dart:_http/websocket_impl.dart:1067:14)
E/flutter (13901): #2 _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (13901): #3 _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (13901): #4 _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter (13901): #5 Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter (13901): #6 Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter (13901): #7 Future._completeWithValue (dart:async/future_impl.dart:529:5)
E/flutter (13901): #8 Future.wait.<anonymous closure> (dart:async/future.dart:410:22)
E/flutter (13901): #9 _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (13901): #10 _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (13901): #11 _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter (13901): #12 Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter (13901): #14 Future._completeWithValue (dart:async/future_impl.dart:529:5)
E/flutter (13901): #15 Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
E/flutter (13901): #16 _rootRun (dart:async/zone.dart:1190:13)
E/flutter (13901): #17 _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (13901): #18 _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (13901): #19 _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (13901): #20 _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (13901): #21 _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)

**Comment by rafay-tariq** [comment]
solved using this 
Actually strict application load balancer policy was applied on AWS
Relaxing it solved the issue
